language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amol9372/react-aws:dev -f Dockerfile.dev .

script:
  - docker run -e CI=true amol9372/react-aws:dev npm run test -- --coverage
