language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f -t amol9372/react-aws:dev Dockerfile.dev .

script:
  - docker run -e CI=true amol9372/react-aws:dev npm run test -- --coverage
